# -*- coding: utf-8; -*-
#
# This file is part of Superdesk.
#
# Copyright 2013, 2014, 2015 Sourcefabric z.u. and contributors.
#
# For the full copyright and license information, please see the
# AUTHORS and LICENSE files distributed with this source code, or
# at https://www.sourcefabric.org/superdesk/license

version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    stream  : ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    filename: logfile.log
    formatter: simple
    maxBytes: 10485760
    backupCount: 5
  file_error:
    class : logging.handlers.RotatingFileHandler
    level: ERROR
    filename: logfile_error.log
    formatter: simple
    maxBytes: 10485760
    backupCount: 5
loggers:
  video-server.ws:
    handlers: [console, file, file_error]
    level: DEBUG
  worker:
    handlers: [console, file, file_error]
    level: WARN

root:
  handlers: [console, file, file_error]
